package net.azisaba.data.provider

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import net.kyori.examination.Examinable
import net.kyori.examination.ExaminableProperty
import java.util.stream.Stream
import kotlin.random.Random

/**
 * Produces floating-point values from a configured distribution.
 */
@Serializable
sealed interface FloatProvider : NumberProvider<Float>, Examinable {
    /**
     * Always returns [value].
     *
     * @property value the value to return
     */
    @Serializable
    @SerialName("Constant")
    data class Constant(override val value: Float) : ConstantNumberProvider<Float>(), FloatProvider

    /**
     * Produces uniformly distributed values from [minInclusive] inclusive to [maxExclusive]
     * exclusive.
     *
     * @property minInclusive the inclusive lower bound
     * @property maxExclusive the exclusive upper bound
     * @throws IllegalArgumentException if [maxExclusive] is not greater than [minInclusive]
     */
    @Serializable
    @SerialName("Uniform")
    data class Uniform(val minInclusive: Float, val maxExclusive: Float) : FloatProvider {
        init {
            require(maxExclusive > minInclusive) {
                "maxExclusive must be greater than minInclusive: [$minInclusive, $maxExclusive]"
            }
        }

        override fun provide(random: Random): Float {
            return random.nextFloat() * (maxExclusive - minInclusive) + minInclusive
        }

        override fun examinableProperties(): Stream<out ExaminableProperty?> {
            return Stream.of(
                ExaminableProperty.of("minInclusive", minInclusive),
                ExaminableProperty.of("maxExclusive", maxExclusive),
            )
        }
    }

    /**
     * Produces normally distributed values clamped to the inclusive range from [min] to [max].
     *
     * @property mean the mean of the normal distribution
     * @property deviation the standard deviation multiplier
     * @property min the inclusive lower clamp bound
     * @property max the inclusive upper clamp bound
     * @throws IllegalArgumentException if [max] is less than [min]
     */
    @Serializable
    @SerialName("ClampedNormal")
    data class ClampedNormal(val mean: Float, val deviation: Float, val min: Float, val max: Float) : FloatProvider {
        init {
            require(max >= min) {
                "max must be greater than or equal to min: [$min, $max]"
            }
        }

        override fun provide(random: Random): Float {
            return (random.nextGaussian().toFloat() * deviation + mean).coerceIn(min, max)
        }

        override fun examinableProperties(): Stream<out ExaminableProperty?> {
            return Stream.of(
                ExaminableProperty.of("mean", mean),
                ExaminableProperty.of("deviation", deviation),
                ExaminableProperty.of("min", min),
                ExaminableProperty.of("max", max),
            )
        }
    }

    /**
     * Produces values by combining two uniform random samples.
     *
     * For a non-negative [plateau], the result follows a symmetric trapezoidal distribution from
     * [min] to [max] with a centered plateau of the requested width. A plateau equal to the full
     * span produces a uniform distribution.
     *
     * @property min the lower bound
     * @property max the upper bound
     * @property plateau the width used by the trapezoidal distribution formula
     * @throws IllegalArgumentException if [max] is less than [min] or [plateau] exceeds the span
     */
    @Serializable
    @SerialName("Trapezoid")
    data class Trapezoid(val min: Float, val max: Float, val plateau: Float) : FloatProvider {
        init {
            require(max >= min) {
                "max must be greater than or equal to min: [$min, $max]"
            }
            require(plateau <= max - min) {
                "plateau must be less than or equal to the full span: [$min, $max]"
            }
        }

        override fun provide(random: Random): Float {
            val span = max - min
            val slope = (span - plateau) / 2.0f
            val base = span - slope
            return min + random.nextFloat() * base + random.nextFloat() * slope
        }

        override fun examinableProperties(): Stream<out ExaminableProperty?> {
            return Stream.of(
                ExaminableProperty.of("min", min),
                ExaminableProperty.of("max", max),
                ExaminableProperty.of("plateau", plateau),
            )
        }
    }

    /**
     * Produces the product of values generated by [values].
     *
     * Providers are evaluated in list order with the same random generator.
     *
     * @property values the non-empty list of providers to multiply
     * @throws IllegalArgumentException if [values] is empty
     */
    @Serializable
    @SerialName("Multiplied")
    data class Multiplied(val values: List<FloatProvider>) : FloatProvider {
        init {
            require(values.isNotEmpty()) {
                "values must not be empty"
            }
        }

        override fun provide(random: Random): Float {
            var product = 1.0f
            for (value in values) {
                product *= value.provide(random)
            }
            return product
        }

        override fun examinableProperties(): Stream<out ExaminableProperty?> {
            return Stream.of(ExaminableProperty.of("values", values))
        }
    }
}
